
[theme]
primaryColor="#ff5100"              # your brand primary
backgroundColor="#221f20"           # page background
secondaryBackgroundColor="#ff2323ff"  # cards/containers
textColor="#FFFEF6"                 # body text
font="sans serif"                   # or "serif"/"monospace"